services:
  # Development service
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: emoji-game-dev
    ports:
      - "8100:8100"
      - "35729:35729"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

  # Production service
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: emoji-game-prod
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

